import ContentService from "@/lib/ContentService";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import SkipToContent from "@/components/SkipToContent";
import Socials from "@/components/Socials";
import RainbowStrip from "@/components/RainbowStrip";
const links = [
  ["About", "#about"],
  ["Projects", "#projects"],
  ["Work", "#work"],
  ["Skills", "#skills"],
  ["Contact", "#contact"],
];

const sectionIds = links.map(([_, id]) => id.slice(1));
const Header = () => {
  return (
    <header>
      <nav>
        <ul>
          <div>LOGO</div>
        </ul>
        <ul id="sections">
          {links.map(([text, href]) => (
            <li key={text}>
              <Link href={href}>{text}</Link>
            </li>
          ))}
        </ul>
      </nav>
    </header>
  );
};

export default function Home({ sections }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SkipToContent href="about" />
      <main id="home" className="container">
      <RainbowStrip ids={sectionIds} />
        <Header />
        <section id="hero" className="centered">
          <hgroup>
            <h1>Oliver Daniel</h1>
            <h2>Full Stack Developer</h2>
          </hgroup>
          <div className="row socials">
            <Socials />
          </div>
        </section>
        <section id="about">
          <h2>ABOUT</h2>
          <div className="grid">
            <div></div>
            <div dangerouslySetInnerHTML={{ __html: sections.about.content }} />
          </div>
        </section>
        <section id="projects">
          <h2>PROJECTS</h2>
        </section>
        <section id="work">
          <h2>WORK HISTORY</h2>
        </section>
        <section id="skills">
          <h2>SKILLS</h2>
        </section>
        <section id="contact">
          <h2>CONTACT</h2>
        </section>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const sections = {
    about: ContentService.getPageData("home/about"),
  };

  return {
    props: {
      sections,
    },
  };
}
